site_name: IF Anciens
site_author: vincent.penelle@u-bordeaux.fr
site_url: https://vincentpenelle.gitlab.io/if-anciens/
site_dir: public
extra_css: [ extra.css ]
use_directory_urls: false

theme:
    # name: mkdocs
    name: readthedocs
    highlightjs: true
    locale: fr
    navigation_depth: 2
    # only for readthedocs
    prev_next_buttons_location: none
    include_homepage_in_sidebar: true
    # titles_only: true     # only for readthedocs
    # logo: gnu.png         # only for readthedocs
    # only for mkdocs
    # nav_style: dark       # only for mkdocs

nav:
    - Parcours IF: https://masterinfo.emi.u-bordeaux.fr/wiki/doku.php?id=if
    - Page Anciens: index.md
    - Promo 2019-2021: 2021/index.md
    - Promo 2018-2020: 2020/index.md
    - Promo 2017-2019: 2019/index.md
    - Promo 2016-2018: 2018/index.md

# disable all plugins (default is ['search'])
plugins: []

# disable ???
# extra:
#   generator: false
